name: Run migrations

on:
  push:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install, build and run migrations
      env:
          POSTGRES_HOST: ${{ secrets.DATABASE_HOST }}
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_NAME: ${{ secrets.DATABASE_NAME }}
      run: |
        npm install
        npm run migration:run
